analyzer:
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
    no_leading_underscores_for_local_identifiers: ignore
    non_constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml
