name: waste_exchange
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  contacts_service: ^0.6.3
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  qr_code_scanner: ^1.0.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
